export const extraneousPhrases3 = [
    "1 of 3",
    "Service Information ... MoreWildfires Impacting Service in the Northwest Territories ... MoreService Alert due to Situation in Ukraine... MoreService Information ... MoreWildfires Impacting Service in the Northwest Territories ... MoreService Alert due to Situation in Ukraine... MoreService Information ... More",
    "/",
    "Menu",
    "a package or search",
    "Searchx",
    "Calculate Cost",
    "View  History",
    "Batch File",
    "Go to",
    "Go to",
    "About UPSOpen the link in a new window",
    "/",
    "Search",
    "Stay Safe - Avoid Fraud and Scams",
    "Received a text,",
    "Track",
    "Numbers",
    "Close",
    "Lorem ipsum",
    "Invalid",
    "Track",
    "Import Tracking Numbers",
    "Recently Tracked",
    "Log in",
    "or",
    "Sign up",
    "to view your recently tracked shipments.",
    "Tracking",
    "Shipping",
    "Help &amp; Support",
    "Communication Preferences",
    "Other UPS Sites",
    "About UPSOpen the link in a new window",
    "Supply Chain SolutionsOpen the link in a new window",
    "UPS JobsOpen the link in a new window",
    "TwitterOpen the link in a new window",
    "InstagramOpen the link in a new window",
    "LinkedInOpen the link in a new window",
    "YouTubeOpen the link in a new window",
    "Global Home",
    "Protect Against Fraud",
    "Website Terms of Use",
    "Privacy Notice",
    "Cookie Settings",
    "Close   This site uses cookies   By continuing,, click on the Cookie Settings link in the footer of any page.",
    "Feedback",
    "the link in a new window",
    "Get Updates",
    "File a Claim",
    "View Details",
    "Another Package",
    "Other Packages in this Shipment",
    "This site uses cookies",
    "By continuing"
];