export const extraneousPhrases2  = [
    "Previous",
    "1 of 3",
    "Next",
    "Service Information ... MoreWildfires Impacting Service in the Northwest Territories ... MoreService Alert due to Situation in Ukraine... MoreService Information ... MoreWildfires Impacting Service in the Northwest Territories ... MoreService Alert due to Situation in Ukraine... MoreService Information ... More",
    "Close",
    "Skip to Main Content",
    "Track a package or search",
    "Log in / Sign up",
    "MenuClose",
    "Track a package or search",
    "SearchClosex",
    "Shipping",
    "Shipping",
    "Create a Shipment",
    "Calculate Shipping Cost",
    "Schedule a Pickup",
    "Find a Location",
    "View Shipping History",
    "Batch File Shipping",
    "Packaging and Shipping Supplies",
    "Manage Customer Orders",
    "How to Ship a Package",
    "How to Ship Internationally",
    "How to Return a Package",
    "Go to Shipping Support",
    "Tracking",
    "Tracking",
    "Track a Package",
    "View All Shipments",
    "Manage with Quantum View",
    "Change a Delivery",
    "Go to Tracking Support",
    "Business Solutions",
    "Business Solutions",
    "Open an Account To Save Up To 52%",
    "Business Shipping Tools",
    "View and Control Your Shipments",
    "Manage Shipments for Large Enterprises",
    "Understand and Pay Bills",
    "File or View a Claim",
    "Start or Grow Your Business",
    "Expand Your Online Business",
    "Pickup and Drop-off Options",
    "Simplify Returns",
    "Support",
    "Support",
    "Understand and Pay Bills",
    "Manage Your Profile",
    "File or View a Claim",
    "Contact Us",
    "Tracking Support",
    "Shipping Support",
    "International Tools and Resources",
    "About UPSOpen the link in a new window",
    "Locations",
    "Canada - English",
    "Canada - English",
    "Canada - Français",
    "Select Another Country or Territory",
    "Log in / Sign up",
    "Track a package or search",
    "SearchClose"
];