export const extraneousPhrases1 = [
    "UPS Freight Less-than-Truckload (“LTL”) transportation services are offered by TFI International Inc., its affiliates or divisions (including without limitation TForce Freight), which are not affiliated with United Parcel Service, Inc. or any of its affiliates, subsidiaries or related entities (“UPS”). UPS assumes no liability in connection with UPS Freight LTL transportation services or any other services offered or provided by TFI International Inc. or its affiliates, divisions, subsidiaries or related entities.",
    "Stay Safe - Avoid Fraud and Scams. Received a text, call or email that seems suspicious? Don't respond to it.",
    "Enter up to 25 tracking numbers, one per line.",
    "This site uses cookies   By continuing, you consent to our use of cookies. To learn more or set your preferences, click on the Cookie Settings link in the footer of any page.",
    "Service Information ... MoreWildfires Impacting Service in the Northwest Territories ... MoreService Alert due to Situation in Ukraine... MoreService Information ... MoreWildfires Impacting Service in the Northwest Territories ... MoreService Alert due to Situation in Ukraine... MoreService Information ... More",
    "Terms and Conditions, Website Terms of Use, Privacy Notice, Cookie Settings",
    "This Site, Tracking, Shipping, Help &amp; Support, Communication Preferences, Other UPS Sites",
    "Connect With Us, TwitterOpen the link in a new window, InstagramOpen the link in a new window, LinkedInOpen the link in a new window, YouTubeOpen the link in a new window",
    "Legal, Global Home, Protect Against Fraud",
    "Copyright ©1994- 2023&nbsp;United Parcel Service of America, Inc. All rights reserved.",
    "Track by Reference Number, Import Tracking Numbers, Other Tracking Services",
    "Skip to Main Content, Track a package or search, Log in / Sign up, MenuClose, Track a package or search, SearchClosex",
    "Create a Shipment, Calculate Shipping Cost, Schedule a Pickup, Find a Location, View Shipping History, Batch File Shipping",
    "Shipping, Create a Shipment, Calculate Shipping Cost, Schedule a Pickup, Find a Location, View Shipping History, Batch File Shipping",
    "Business Solutions, Open an Account To Save Up To 52%, Business Shipping Tools, View and Control Your Shipments",
    "Support, Understand and Pay Bills, Manage Your Profile, File or View a Claim, Contact Us, Tracking Support, Shipping Support",
    "Packaging and Shipping Supplies, Manage Customer Orders, How to Ship a Package, How to Ship Internationally, How to Return a Package",
    "Tracking, Track a Package, View All Shipments, Manage with Quantum View, Change a Delivery, Go to Tracking Support",
    "Canada - English, Canada - English, Canada - Français, Select Another Country or Territory",
    "Please provide a tracking number.",
    "1 of 25 tracking numbers entered.",
    "Track a package or search, SearchClose, Track a package or search",
    "Manage Shipments for Large Enterprises, Understand and Pay Bills, File or View a Claim, Start or Grow Your Business",
    "Log in or Sign up to view your recently tracked shipments.",
    "Expand Your Online Business, Pickup and Drop-off Options, Simplify Returns",
    "About UPSOpen the link in a new window, Supply Chain SolutionsOpen the link in a new window, UPS JobsOpen the link in a new window",
    "Close, Skip to Main Content, Track a package or search, Log in / Sign up, MenuClose, Track a package or search, SearchClosex",
    "Previous, 1 of 3, Next",
    "Tips to Avoid Fraud",
    "Track",
    "Help",
    "Close",
    "Invalid",
    "Track",
    "Log in",
    "or",
    "Sign up"
];